---

- hosts: all
  become: true

  tasks:

    - name: Hello
      debug:
        msg: hello

    - name: Disable SELinux
      selinux:
        state: disabled 
      register: selinux

    - name: Need to reboot?
      debug:
        msg: Yes
      when: selinux.changed == true

    - name: Reboot if we need to
      shell: sleep 2 && /sbin/shutdown -r now
      async: 1
      poll: 0
      when: selinux.changed == true

    - name: Wait for reboot to complete
      wait_for:
        timeout: 300
        host: "{{ ansible_ssh_host }}"
        port: 22
        delay: 10
      delegate_to: localhost
      when: selinux.changed == true
      become: false

    - name: Check if EPEL repo is already configured
      stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel_repofile_result

    - name: Install EPEL repo
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      register: result
      when: not epel_repofile_result.stat.exists

    - name: Import EPEL GPG key
      rpm_key:
        key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        state: present
      when: not epel_repofile_result.stat.exists

    - name: Install the latest version of Ansible
      yum:
        name: ansible
        state: latest

    - name: Bye
      debug:
        msg: bye
