---

- hosts: all
  become: true

  tasks:

    - name: Hello
      debug:
        msg: hello

    - name: Disable SELinux
      selinux:
        state: disabled 
      register: selinux

    - name: Need to reboot?
      debug:
        msg: Yes
      when: selinux.changed == true

    - name: Reboot if we need to
      shell: sleep 2 && /sbin/shutdown -r now
      async: 1
      poll: 0
      when: selinux.changed == true

    - name: Wait for reboot to complete
      wait_for:
        timeout: 300
        host: "{{ ansible_ssh_host }}"
        port: 22
        delay: 20
      delegate_to: localhost
      when: selinux.changed == true
      become: false

    - name: Check if EPEL repo is already configured
      stat:
        path: /etc/yum.repos.d/epel.repo
      register: epel_repofile_result

    - name: Install EPEL repo
      yum:
        name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      register: result
      when: not epel_repofile_result.stat.exists

    - name: Import EPEL GPG key
      rpm_key:
        key: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
        state: present
      when: not epel_repofile_result.stat.exists

    - name: Install the latest version of some packages
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - ansible

    # Note: This "creates" will probably change... and the dir is hard coded multiple times... sorry
    - name: Download and extract ansible tower setup
      unarchive:
        src: https://releases.ansible.com/ansible-tower/setup-bundle/ansible-tower-setup-bundle-latest.el7.tar.gz
        dest: /opt
        creates: /opt/ansible-tower-setup-bundle-3.2.3-1.el7/setup.sh
        remote_src: yes

    - name: Set admin password for install
      lineinfile:
        path: /opt/ansible-tower-setup-bundle-3.2.3-1.el7/inventory
        regexp: "^admin_password=''"
        line: "admin_password='password'"
        backrefs: yes

    - name: Set pg password for install
      lineinfile:
        path: /opt/ansible-tower-setup-bundle-3.2.3-1.el7/inventory
        regexp: "^pg_password=''"
        line: "pg_password='password'"
        backrefs: yes

    - name: Set rabbitmq password for install
      lineinfile:
        path: /opt/ansible-tower-setup-bundle-3.2.3-1.el7/inventory
        regexp: "^rabbitmq_password=''"
        line: "rabbitmq_password='password'"
        backrefs: yes

    - name: Bye
      debug:
        msg: bye
